<?php
use Illuminate\Database\Seeder;

class OptionsTableSeeder extends Seeder {
	public function  run() {
		//Tablo verilerini temizleyelim
		DB::table( 'options' )->delete();
		// Konsol çıktısını verelim
		$this->command->info( 'options tablosu temizlendi' );
		// Birincil mail adresi oluşturalım
		preg_match('(([a-zA-Z0-9-]+\.)([a-zA-Z]+)$)',Config::get('app.url') , $mainMailAddress);
		$mainMailAddress= 'info@'.$mainMailAddress[0];
		//Veri tabanına verilerimizi ekleyelim
		DB::table( 'options' )->insert( array(
				array(
						'optionKey'   => 'cities',
						'optionValue' => serialize( array( '', 'Adana', 'Adıyaman', 'Afyonkarahisar', 'Ağrı', 'Amasya', 'Ankara', 'Antalya', 'Artvin',
								'Aydın', 'Balıkesir', 'Bilecik', 'Bingöl', 'Bitlis', 'Bolu', 'Burdur', 'Bursa', 'Çanakkale',
								'Çankırı', 'Çorum', 'Denizli', 'Diyarbakır', 'Edirne', 'Elazığ', 'Erzincan', 'Erzurum', 'Eskişehir',
								'Gaziantep', 'Giresun', 'Gümüşhane', 'Hakkari', 'Hatay', 'Isparta', 'İçel', 'İstanbul', 'İzmir',
								'Kars', 'Kastamonu', 'Kayseri', 'Kırklareli', 'Kırşehir', 'Kocaeli', 'Konya', 'Kütahya', 'Malatya',
								'Manisa', 'Kahramanmaraş', 'Mardin', 'Muğla', 'Muş', 'Nevşehir', 'Niğde', 'Ordu', 'Rize', 'Sakarya',
								'Samsun', 'Siirt', 'Sinop', 'Sivas', 'Tekirdağ', 'Tokat', 'Trabzon', 'Tunceli', 'Şanlıurfa', 'Uşak',
								'Van', 'Yozgat', 'Zonguldak', 'Aksaray', 'Bayburt', 'Karaman', 'Kırıkkale', 'Batman', 'Şırnak',
								'Bartın', 'Ardahan', 'Iğdır', 'Yalova', 'Karabük', 'Kilis', 'Osmaniye', 'Düzce'
						) ),
						'optionType'  => 'general',
						'created_at'  => date( 'Y-m-d H:i:s' )
				),
				array(
						'optionKey'   => 'counties',
						'optionValue' => serialize( array(
								1  =>
										array(
												'Seyhan'     => 'Seyhan',
												'Ceyhan'     => 'Ceyhan',
												'Feke'       => 'Feke',
												'Karaisalı'  => 'Karaisalı',
												'Karataş'    => 'Karataş',
												'Kozan'      => 'Kozan',
												'Pozantı'    => 'Pozantı',
												'Saimbeyli'  => 'Saimbeyli',
												'Tufanbeyli' => 'Tufanbeyli',
												'Yumurtalık' => 'Yumurtalık',
												'Yüreğir'    => 'Yüreğir',
												'Aladağ'     => 'Aladağ',
												'İmamoğlu'   => 'İmamoğlu',
												'Sarıçam'    => 'Sarıçam',
												'Çukurova'   => 'Çukurova',
										),
								2  =>
										array(
												'Adıyaman Merkez'    => 'Adıyaman Merkez',
												'Besni'              => 'Besni',
												'Çelikhan'           => 'Çelikhan',
												'Gerger'             => 'Gerger',
												'Gölbaşı / Adıyaman' => 'Gölbaşı / Adıyaman',
												'Kahta'              => 'Kahta',
												'Samsat'             => 'Samsat',
												'Sincik'             => 'Sincik',
												'Tut'                => 'Tut',
										),
								3  =>
										array(
												'Afyonkarahisar Merkez'  => 'Afyonkarahisar Merkez',
												'Bolvadin'               => 'Bolvadin',
												'Çay'                    => 'Çay',
												'Dazkırı'                => 'Dazkırı',
												'Dinar'                  => 'Dinar',
												'Emirdağ'                => 'Emirdağ',
												'İhsaniye'               => 'İhsaniye',
												'Sandıklı'               => 'Sandıklı',
												'Sinanpaşa'              => 'Sinanpaşa',
												'Sultandağı'             => 'Sultandağı',
												'Şuhut'                  => 'Şuhut',
												'Başmakçı'               => 'Başmakçı',
												'Bayat / Afyonkarahisar' => 'Bayat / Afyonkarahisar',
												'İscehisar'              => 'İscehisar',
												'Çobanlar'               => 'Çobanlar',
												'Evciler'                => 'Evciler',
												'Hocalar'                => 'Hocalar',
												'Kızılören'              => 'Kızılören',
										),
								4  =>
										array(
												'Ağrı Merkez' => 'Ağrı Merkez',
												'Diyadin'     => 'Diyadin',
												'Doğubayazıt' => 'Doğubayazıt',
												'Eleşkirt'    => 'Eleşkirt',
												'Hamur'       => 'Hamur',
												'Patnos'      => 'Patnos',
												'Taşlıçay'    => 'Taşlıçay',
												'Tutak'       => 'Tutak',
										),
								5  =>
										array(
												'Amasya Merkez' => 'Amasya Merkez',
												'Göynücek'      => 'Göynücek',
												'Gümüşhacıköy'  => 'Gümüşhacıköy',
												'Merzifon'      => 'Merzifon',
												'Suluova'       => 'Suluova',
												'Taşova'        => 'Taşova',
												'Hamamözü'      => 'Hamamözü',
										),
								6  =>
										array(
												'Altındağ'         => 'Altındağ',
												'Ayaş'             => 'Ayaş',
												'Bala'             => 'Bala',
												'Beypazarı'        => 'Beypazarı',
												'Çamlıdere'        => 'Çamlıdere',
												'Çankaya'          => 'Çankaya',
												'Çubuk'            => 'Çubuk',
												'Elmadağ'          => 'Elmadağ',
												'Güdül'            => 'Güdül',
												'Haymana'          => 'Haymana',
												'Kalecik'          => 'Kalecik',
												'Kızılcahamam'     => 'Kızılcahamam',
												'Nallıhan'         => 'Nallıhan',
												'Polatlı'          => 'Polatlı',
												'Şereflikoçhisar'  => 'Şereflikoçhisar',
												'Yenimahalle'      => 'Yenimahalle',
												'Gölbaşı / Ankara' => 'Gölbaşı / Ankara',
												'Keçiören'         => 'Keçiören',
												'Mamak'            => 'Mamak',
												'Sincan'           => 'Sincan',
												'Kazan'            => 'Kazan',
												'Akyurt'           => 'Akyurt',
												'Etimesgut'        => 'Etimesgut',
												'Evren'            => 'Evren',
												'Pursaklar'        => 'Pursaklar',
										),
								7  =>
										array(
												'Akseki'          => 'Akseki',
												'Alanya'          => 'Alanya',
												'Elmalı'          => 'Elmalı',
												'Finike'          => 'Finike',
												'Gazipaşa'        => 'Gazipaşa',
												'Gündoğmuş'       => 'Gündoğmuş',
												'Kaş'             => 'Kaş',
												'Korkuteli'       => 'Korkuteli',
												'Kumluca'         => 'Kumluca',
												'Manavgat'        => 'Manavgat',
												'Serik'           => 'Serik',
												'Demre'           => 'Demre',
												'İbradı'          => 'İbradı',
												'Kemer / Antalya' => 'Kemer / Antalya',
												'Aksu / Antalya'  => 'Aksu / Antalya',
												'Döşemealtı'      => 'Döşemealtı',
												'Kepez'           => 'Kepez',
												'Konyaaltı'       => 'Konyaaltı',
												'Muratpaşa'       => 'Muratpaşa',
										),
								8  =>
										array(
												'Ardanuç'       => 'Ardanuç',
												'Arhavi'        => 'Arhavi',
												'Artvin Merkez' => 'Artvin Merkez',
												'Borçka'        => 'Borçka',
												'Hopa'          => 'Hopa',
												'Şavşat'        => 'Şavşat',
												'Yusufeli'      => 'Yusufeli',
												'Murgul'        => 'Murgul',
										),
								9  =>
										array(
												'Bozdoğan'          => 'Bozdoğan',
												'Çine'              => 'Çine',
												'Germencik'         => 'Germencik',
												'Karacasu'          => 'Karacasu',
												'Koçarlı'           => 'Koçarlı',
												'Kuşadası'          => 'Kuşadası',
												'Kuyucak'           => 'Kuyucak',
												'Nazilli'           => 'Nazilli',
												'Söke'              => 'Söke',
												'Sultanhisar'       => 'Sultanhisar',
												'Yenipazar / Aydın' => 'Yenipazar / Aydın',
												'Buharkent'         => 'Buharkent',
												'İncirliova'        => 'İncirliova',
												'Karpuzlu'          => 'Karpuzlu',
												'Köşk'              => 'Köşk',
												'Didim'             => 'Didim',
												'Efeler'            => 'Efeler',
										),
								10 =>
										array(
												'Ayvalık'             => 'Ayvalık',
												'Balya'               => 'Balya',
												'Bandırma'            => 'Bandırma',
												'Bigadiç'             => 'Bigadiç',
												'Burhaniye'           => 'Burhaniye',
												'Dursunbey'           => 'Dursunbey',
												'Edremit / Balıkesir' => 'Edremit / Balıkesir',
												'Erdek'               => 'Erdek',
												'Gönen / Balıkesir'   => 'Gönen / Balıkesir',
												'Havran'              => 'Havran',
												'İvrindi'             => 'İvrindi',
												'Kepsut'              => 'Kepsut',
												'Manyas'              => 'Manyas',
												'Savaştepe'           => 'Savaştepe',
												'Sındırgı'            => 'Sındırgı',
												'Susurluk'            => 'Susurluk',
												'Marmara'             => 'Marmara',
												'Gömeç'               => 'Gömeç',
												'Altıeylül'           => 'Altıeylül',
												'Karesi'              => 'Karesi',
										),
								11 =>
										array(
												'Bilecik Merkez'      => 'Bilecik Merkez',
												'Bozüyük'             => 'Bozüyük',
												'Gölpazarı'           => 'Gölpazarı',
												'Osmaneli'            => 'Osmaneli',
												'Pazaryeri'           => 'Pazaryeri',
												'Söğüt'               => 'Söğüt',
												'Yenipazar / Bilecik' => 'Yenipazar / Bilecik',
												'İnhisar'             => 'İnhisar',
										),
								12 =>
										array(
												'Bingöl Merkez' => 'Bingöl Merkez',
												'Genç'          => 'Genç',
												'Karlıova'      => 'Karlıova',
												'Kiğı'          => 'Kiğı',
												'Solhan'        => 'Solhan',
												'Adaklı'        => 'Adaklı',
												'Yayladere'     => 'Yayladere',
												'Yedisu'        => 'Yedisu',
										),
								13 =>
										array(
												'Adilcevaz'     => 'Adilcevaz',
												'Ahlat'         => 'Ahlat',
												'Bitlis Merkez' => 'Bitlis Merkez',
												'Hizan'         => 'Hizan',
												'Mutki'         => 'Mutki',
												'Tatvan'        => 'Tatvan',
												'Güroymak'      => 'Güroymak',
										),
								14 =>
										array(
												'Bolu Merkez' => 'Bolu Merkez',
												'Gerede'      => 'Gerede',
												'Göynük'      => 'Göynük',
												'Kıbrıscık'   => 'Kıbrıscık',
												'Mengen'      => 'Mengen',
												'Mudurnu'     => 'Mudurnu',
												'Seben'       => 'Seben',
												'Dörtdivan'   => 'Dörtdivan',
												'Yeniçağa'    => 'Yeniçağa',
										),
								15 =>
										array(
												'Ağlasun'             => 'Ağlasun',
												'Bucak'               => 'Bucak',
												'Burdur Merkez'       => 'Burdur Merkez',
												'Gölhisar'            => 'Gölhisar',
												'Tefenni'             => 'Tefenni',
												'Yeşilova'            => 'Yeşilova',
												'Karamanlı'           => 'Karamanlı',
												'Kemer / Burdur'      => 'Kemer / Burdur',
												'Altınyayla / Burdur' => 'Altınyayla / Burdur',
												'Çavdır'              => 'Çavdır',
												'Çeltikçi'            => 'Çeltikçi',
										),
								16 =>
										array(
												'Gemlik'            => 'Gemlik',
												'İnegöl'            => 'İnegöl',
												'İznik'             => 'İznik',
												'Karacabey'         => 'Karacabey',
												'Keles'             => 'Keles',
												'Mudanya'           => 'Mudanya',
												'Mustafakemalpaşa'  => 'Mustafakemalpaşa',
												'Orhaneli'          => 'Orhaneli',
												'Orhangazi'         => 'Orhangazi',
												'Yenişehir / Bursa' => 'Yenişehir / Bursa',
												'Büyükorhan'        => 'Büyükorhan',
												'Harmancık'         => 'Harmancık',
												'Nilüfer'           => 'Nilüfer',
												'Osmangazi'         => 'Osmangazi',
												'Yıldırım'          => 'Yıldırım',
												'Gürsu'             => 'Gürsu',
												'Kestel'            => 'Kestel',
										),
								17 =>
										array(
												'Ayvacık / Çanakkale' => 'Ayvacık / Çanakkale',
												'Bayramiç'            => 'Bayramiç',
												'Biga'                => 'Biga',
												'Bozcaada'            => 'Bozcaada',
												'Çan'                 => 'Çan',
												'Çanakkale Merkez'    => 'Çanakkale Merkez',
												'Eceabat'             => 'Eceabat',
												'Ezine'               => 'Ezine',
												'Gelibolu'            => 'Gelibolu',
												'Gökçeada'            => 'Gökçeada',
												'Lapseki'             => 'Lapseki',
												'Yenice / Çanakkale'  => 'Yenice / Çanakkale',
										),
								18 =>
										array(
												'Çankırı Merkez' => 'Çankırı Merkez',
												'Çerkeş'         => 'Çerkeş',
												'Eldivan'        => 'Eldivan',
												'Ilgaz'          => 'Ilgaz',
												'Kurşunlu'       => 'Kurşunlu',
												'Orta'           => 'Orta',
												'Şabanözü'       => 'Şabanözü',
												'Yapraklı'       => 'Yapraklı',
												'Atkaracalar'    => 'Atkaracalar',
												'Kızılırmak'     => 'Kızılırmak',
												'Bayramören'     => 'Bayramören',
												'Korgun'         => 'Korgun',
										),
								19 =>
										array(
												'Alaca'           => 'Alaca',
												'Bayat / Çorum'   => 'Bayat / Çorum',
												'Çorum Merkez'    => 'Çorum Merkez',
												'İskilip'         => 'İskilip',
												'Kargı'           => 'Kargı',
												'Mecitözü'        => 'Mecitözü',
												'Ortaköy / Çorum' => 'Ortaköy / Çorum',
												'Osmancık'        => 'Osmancık',
												'Sungurlu'        => 'Sungurlu',
												'Boğazkale'       => 'Boğazkale',
												'Uğurludağ'       => 'Uğurludağ',
												'Dodurga'         => 'Dodurga',
												'Laçin'           => 'Laçin',
												'Oğuzlar'         => 'Oğuzlar',
										),
								20 =>
										array(
												'Acıpayam'          => 'Acıpayam',
												'Buldan'            => 'Buldan',
												'Çal'               => 'Çal',
												'Çameli'            => 'Çameli',
												'Çardak'            => 'Çardak',
												'Çivril'            => 'Çivril',
												'Güney'             => 'Güney',
												'Kale / Denizli'    => 'Kale / Denizli',
												'Sarayköy'          => 'Sarayköy',
												'Tavas'             => 'Tavas',
												'Babadağ'           => 'Babadağ',
												'Bekilli'           => 'Bekilli',
												'Honaz'             => 'Honaz',
												'Serinhisar'        => 'Serinhisar',
												'Pamukkale'         => 'Pamukkale',
												'Baklan'            => 'Baklan',
												'Beyağaç'           => 'Beyağaç',
												'Bozkurt / Denizli' => 'Bozkurt / Denizli',
												'Merkezefendi'      => 'Merkezefendi',
										),
								21 =>
										array(
												'Bismil'                 => 'Bismil',
												'Çermik'                 => 'Çermik',
												'Çınar'                  => 'Çınar',
												'Çüngüş'                 => 'Çüngüş',
												'Dicle'                  => 'Dicle',
												'Ergani'                 => 'Ergani',
												'Hani'                   => 'Hani',
												'Hazro'                  => 'Hazro',
												'Kulp'                   => 'Kulp',
												'Lice'                   => 'Lice',
												'Silvan'                 => 'Silvan',
												'Eğil'                   => 'Eğil',
												'Kocaköy'                => 'Kocaköy',
												'Bağlar'                 => 'Bağlar',
												'Kayapınar'              => 'Kayapınar',
												'Sur'                    => 'Sur',
												'Yenişehir / Diyarbakır' => 'Yenişehir / Diyarbakır',
										),
								22 =>
										array(
												'Edirne Merkez' => 'Edirne Merkez',
												'Enez'          => 'Enez',
												'Havsa'         => 'Havsa',
												'İpsala'        => 'İpsala',
												'Keşan'         => 'Keşan',
												'Lalapaşa'      => 'Lalapaşa',
												'Meriç'         => 'Meriç',
												'Uzunköprü'     => 'Uzunköprü',
												'Süloğlu'       => 'Süloğlu',
										),
								23 =>
										array(
												'Ağın'          => 'Ağın',
												'Baskil'        => 'Baskil',
												'Elazığ Merkez' => 'Elazığ Merkez',
												'Karakoçan'     => 'Karakoçan',
												'Keban'         => 'Keban',
												'Maden'         => 'Maden',
												'Palu'          => 'Palu',
												'Sivrice'       => 'Sivrice',
												'Arıcak'        => 'Arıcak',
												'Kovancılar'    => 'Kovancılar',
												'Alacakaya'     => 'Alacakaya',
										),
								24 =>
										array(
												'Çayırlı'         => 'Çayırlı',
												'Erzincan Merkez' => 'Erzincan Merkez',
												'İliç'            => 'İliç',
												'Kemah'           => 'Kemah',
												'Kemaliye'        => 'Kemaliye',
												'Refahiye'        => 'Refahiye',
												'Tercan'          => 'Tercan',
												'Üzümlü'          => 'Üzümlü',
												'Otlukbeli'       => 'Otlukbeli',
										),
								25 =>
										array(
												'Aşkale'     => 'Aşkale',
												'Çat'        => 'Çat',
												'Hınıs'      => 'Hınıs',
												'Horasan'    => 'Horasan',
												'İspir'      => 'İspir',
												'Karayazı'   => 'Karayazı',
												'Narman'     => 'Narman',
												'Oltu'       => 'Oltu',
												'Olur'       => 'Olur',
												'Pasinler'   => 'Pasinler',
												'Şenkaya'    => 'Şenkaya',
												'Tekman'     => 'Tekman',
												'Tortum'     => 'Tortum',
												'Karaçoban'  => 'Karaçoban',
												'Uzundere'   => 'Uzundere',
												'Pazaryolu'  => 'Pazaryolu',
												'Aziziye'    => 'Aziziye',
												'Köprüköy'   => 'Köprüköy',
												'Palandöken' => 'Palandöken',
												'Yakutiye'   => 'Yakutiye',
										),
								26 =>
										array(
												'Çifteler'   => 'Çifteler',
												'Mahmudiye'  => 'Mahmudiye',
												'Mihalıççık' => 'Mihalıççık',
												'Sarıcakaya' => 'Sarıcakaya',
												'Seyitgazi'  => 'Seyitgazi',
												'Sivrihisar' => 'Sivrihisar',
												'Alpu'       => 'Alpu',
												'Beylikova'  => 'Beylikova',
												'İnönü'      => 'İnönü',
												'Günyüzü'    => 'Günyüzü',
												'Han'        => 'Han',
												'Mihalgazi'  => 'Mihalgazi',
												'Odunpazarı' => 'Odunpazarı',
												'Tepebaşı'   => 'Tepebaşı',
										),
								27 =>
										array(
												'Araban'     => 'Araban',
												'İslahiye'   => 'İslahiye',
												'Nizip'      => 'Nizip',
												'Oğuzeli'    => 'Oğuzeli',
												'Yavuzeli'   => 'Yavuzeli',
												'Şahinbey'   => 'Şahinbey',
												'Şehitkamil' => 'Şehitkamil',
												'Karkamış'   => 'Karkamış',
												'Nurdağı'    => 'Nurdağı',
										),
								28 =>
										array(
												'Alucra'         => 'Alucra',
												'Bulancak'       => 'Bulancak',
												'Dereli'         => 'Dereli',
												'Espiye'         => 'Espiye',
												'Eynesil'        => 'Eynesil',
												'Giresun Merkez' => 'Giresun Merkez',
												'Görele'         => 'Görele',
												'Keşap'          => 'Keşap',
												'Şebinkarahisar' => 'Şebinkarahisar',
												'Tirebolu'       => 'Tirebolu',
												'Piraziz'        => 'Piraziz',
												'Yağlıdere'      => 'Yağlıdere',
												'Çamoluk'        => 'Çamoluk',
												'Çanakçı'        => 'Çanakçı',
												'Doğankent'      => 'Doğankent',
												'Güce'           => 'Güce',
										),
								29 =>
										array(
												'Gümüşhane Merkez' => 'Gümüşhane Merkez',
												'Kelkit'           => 'Kelkit',
												'Şiran'            => 'Şiran',
												'Torul'            => 'Torul',
												'Köse'             => 'Köse',
												'Kürtün'           => 'Kürtün',
										),
								30 =>
										array(
												'Çukurca'        => 'Çukurca',
												'Hakkari Merkez' => 'Hakkari Merkez',
												'Şemdinli'       => 'Şemdinli',
												'Yüksekova'      => 'Yüksekova',
										),
								31 =>
										array(
												'Altınözü'   => 'Altınözü',
												'Dörtyol'    => 'Dörtyol',
												'Hassa'      => 'Hassa',
												'İskenderun' => 'İskenderun',
												'Kırıkhan'   => 'Kırıkhan',
												'Reyhanlı'   => 'Reyhanlı',
												'Samandağ'   => 'Samandağ',
												'Yayladağı'  => 'Yayladağı',
												'Erzin'      => 'Erzin',
												'Belen'      => 'Belen',
												'Kumlu'      => 'Kumlu',
												'Antakya'    => 'Antakya',
												'Arsuz'      => 'Arsuz',
												'Defne'      => 'Defne',
												'Payas'      => 'Payas',
										),
								32 =>
										array(
												'Atabey'          => 'Atabey',
												'Eğirdir'         => 'Eğirdir',
												'Gelendost'       => 'Gelendost',
												'Isparta Merkez'  => 'Isparta Merkez',
												'Keçiborlu'       => 'Keçiborlu',
												'Senirkent'       => 'Senirkent',
												'Sütçüler'        => 'Sütçüler',
												'Şarkikaraağaç'   => 'Şarkikaraağaç',
												'Uluborlu'        => 'Uluborlu',
												'Yalvaç'          => 'Yalvaç',
												'Aksu / Isparta'  => 'Aksu / Isparta',
												'Gönen / Isparta' => 'Gönen / Isparta',
												'Yenişarbademli'  => 'Yenişarbademli',
										),
								33 =>
										array(
												'Anamur'             => 'Anamur',
												'Erdemli'            => 'Erdemli',
												'Gülnar'             => 'Gülnar',
												'Mut'                => 'Mut',
												'Silifke'            => 'Silifke',
												'Tarsus'             => 'Tarsus',
												'Aydıncık / Mersin'  => 'Aydıncık / Mersin',
												'Bozyazı'            => 'Bozyazı',
												'Çamlıyayla'         => 'Çamlıyayla',
												'Akdeniz'            => 'Akdeniz',
												'Mezitli'            => 'Mezitli',
												'Toroslar'           => 'Toroslar',
												'Yenişehir / Mersin' => 'Yenişehir / Mersin',
										),
								34 =>
										array(
												'Adalar'        => 'Adalar',
												'Bakırköy'      => 'Bakırköy',
												'Beşiktaş'      => 'Beşiktaş',
												'Beykoz'        => 'Beykoz',
												'Beyoğlu'       => 'Beyoğlu',
												'Çatalca'       => 'Çatalca',
												'Eyüp'          => 'Eyüp',
												'Fatih'         => 'Fatih',
												'Gaziosmanpaşa' => 'Gaziosmanpaşa',
												'Kadıköy'       => 'Kadıköy',
												'Kartal'        => 'Kartal',
												'Sarıyer'       => 'Sarıyer',
												'Silivri'       => 'Silivri',
												'Şile'          => 'Şile',
												'Şişli'         => 'Şişli',
												'Üsküdar'       => 'Üsküdar',
												'Zeytinburnu'   => 'Zeytinburnu',
												'Büyükçekmece'  => 'Büyükçekmece',
												'Kağıthane'     => 'Kağıthane',
												'Küçükçekmece'  => 'Küçükçekmece',
												'Pendik'        => 'Pendik',
												'Ümraniye'      => 'Ümraniye',
												'Bayrampaşa'    => 'Bayrampaşa',
												'Avcılar'       => 'Avcılar',
												'Bağcılar'      => 'Bağcılar',
												'Bahçelievler'  => 'Bahçelievler',
												'Güngören'      => 'Güngören',
												'Maltepe'       => 'Maltepe',
												'Sultanbeyli'   => 'Sultanbeyli',
												'Tuzla'         => 'Tuzla',
												'Esenler'       => 'Esenler',
												'Arnavutköy'    => 'Arnavutköy',
												'Ataşehir'      => 'Ataşehir',
												'Başakşehir'    => 'Başakşehir',
												'Beylikdüzü'    => 'Beylikdüzü',
												'Çekmeköy'      => 'Çekmeköy',
												'Esenyurt'      => 'Esenyurt',
												'Sancaktepe'    => 'Sancaktepe',
												'Sultangazi'    => 'Sultangazi',
										),
								35 =>
										array(
												'Aliağa'      => 'Aliağa',
												'Bayındır'    => 'Bayındır',
												'Bergama'     => 'Bergama',
												'Bornova'     => 'Bornova',
												'Çeşme'       => 'Çeşme',
												'Dikili'      => 'Dikili',
												'Foça'        => 'Foça',
												'Karaburun'   => 'Karaburun',
												'Karşıyaka'   => 'Karşıyaka',
												'Kemalpaşa'   => 'Kemalpaşa',
												'Kınık'       => 'Kınık',
												'Kiraz'       => 'Kiraz',
												'Menemen'     => 'Menemen',
												'Ödemiş'      => 'Ödemiş',
												'Seferihisar' => 'Seferihisar',
												'Selçuk'      => 'Selçuk',
												'Tire'        => 'Tire',
												'Torbalı'     => 'Torbalı',
												'Urla'        => 'Urla',
												'Beydağ'      => 'Beydağ',
												'Buca'        => 'Buca',
												'Konak'       => 'Konak',
												'Menderes'    => 'Menderes',
												'Balçova'     => 'Balçova',
												'Çiğli'       => 'Çiğli',
												'Gaziemir'    => 'Gaziemir',
												'Narlıdere'   => 'Narlıdere',
												'Güzelbahçe'  => 'Güzelbahçe',
												'Bayraklı'    => 'Bayraklı',
												'Karabağlar'  => 'Karabağlar',
										),
								36 =>
										array(
												'Arpaçay'     => 'Arpaçay',
												'Digor'       => 'Digor',
												'Kağızman'    => 'Kağızman',
												'Kars Merkez' => 'Kars Merkez',
												'Sarıkamış'   => 'Sarıkamış',
												'Selim'       => 'Selim',
												'Susuz'       => 'Susuz',
												'Akyaka'      => 'Akyaka',
										),
								37 =>
										array(
												'Abana'                 => 'Abana',
												'Araç'                  => 'Araç',
												'Azdavay'               => 'Azdavay',
												'Bozkurt / Kastamonu'   => 'Bozkurt / Kastamonu',
												'Cide'                  => 'Cide',
												'Çatalzeytin'           => 'Çatalzeytin',
												'Daday'                 => 'Daday',
												'Devrekani'             => 'Devrekani',
												'İnebolu'               => 'İnebolu',
												'Kastamonu Merkez'      => 'Kastamonu Merkez',
												'Küre'                  => 'Küre',
												'Taşköprü'              => 'Taşköprü',
												'Tosya'                 => 'Tosya',
												'İhsangazi'             => 'İhsangazi',
												'Pınarbaşı / Kastamonu' => 'Pınarbaşı / Kastamonu',
												'Şenpazar'              => 'Şenpazar',
												'Ağlı'                  => 'Ağlı',
												'Doğanyurt'             => 'Doğanyurt',
												'Hanönü'                => 'Hanönü',
												'Seydiler'              => 'Seydiler',
										),
								38 =>
										array(
												'Bünyan'              => 'Bünyan',
												'Develi'              => 'Develi',
												'Felahiye'            => 'Felahiye',
												'İncesu'              => 'İncesu',
												'Pınarbaşı / Kayseri' => 'Pınarbaşı / Kayseri',
												'Sarıoğlan'           => 'Sarıoğlan',
												'Sarız'               => 'Sarız',
												'Tomarza'             => 'Tomarza',
												'Yahyalı'             => 'Yahyalı',
												'Yeşilhisar'          => 'Yeşilhisar',
												'Akkışla'             => 'Akkışla',
												'Talas'               => 'Talas',
												'Kocasinan'           => 'Kocasinan',
												'Melikgazi'           => 'Melikgazi',
												'Hacılar'             => 'Hacılar',
												'Özvatan'             => 'Özvatan',
										),
								39 =>
										array(
												'Babaeski'          => 'Babaeski',
												'Demirköy'          => 'Demirköy',
												'Kırklareli Merkez' => 'Kırklareli Merkez',
												'Kofçaz'            => 'Kofçaz',
												'Lüleburgaz'        => 'Lüleburgaz',
												'Pehlivanköy'       => 'Pehlivanköy',
												'Pınarhisar'        => 'Pınarhisar',
												'Vize'              => 'Vize',
										),
								40 =>
										array(
												'Çiçekdağı'       => 'Çiçekdağı',
												'Kaman'           => 'Kaman',
												'Kırşehir Merkez' => 'Kırşehir Merkez',
												'Mucur'           => 'Mucur',
												'Akpınar'         => 'Akpınar',
												'Akçakent'        => 'Akçakent',
												'Boztepe'         => 'Boztepe',
										),
								41 =>
										array(
												'Gebze'      => 'Gebze',
												'Gölcük'     => 'Gölcük',
												'Kandıra'    => 'Kandıra',
												'Karamürsel' => 'Karamürsel',
												'Körfez'     => 'Körfez',
												'Derince'    => 'Derince',
												'Başiskele'  => 'Başiskele',
												'Çayırova'   => 'Çayırova',
												'Darıca'     => 'Darıca',
												'Dilovası'   => 'Dilovası',
												'İzmit'      => 'İzmit',
												'Kartepe'    => 'Kartepe',
										),
								42 =>
										array(
												'Akşehir'        => 'Akşehir',
												'Beyşehir'       => 'Beyşehir',
												'Bozkır'         => 'Bozkır',
												'Cihanbeyli'     => 'Cihanbeyli',
												'Çumra'          => 'Çumra',
												'Doğanhisar'     => 'Doğanhisar',
												'Ereğli / Konya' => 'Ereğli / Konya',
												'Hadim'          => 'Hadim',
												'Ilgın'          => 'Ilgın',
												'Kadınhanı'      => 'Kadınhanı',
												'Karapınar'      => 'Karapınar',
												'Kulu'           => 'Kulu',
												'Sarayönü'       => 'Sarayönü',
												'Seydişehir'     => 'Seydişehir',
												'Yunak'          => 'Yunak',
												'Akören'         => 'Akören',
												'Altınekin'      => 'Altınekin',
												'Derebucak'      => 'Derebucak',
												'Hüyük'          => 'Hüyük',
												'Karatay'        => 'Karatay',
												'Meram'          => 'Meram',
												'Selçuklu'       => 'Selçuklu',
												'Taşkent'        => 'Taşkent',
												'Ahırlı'         => 'Ahırlı',
												'Çeltik'         => 'Çeltik',
												'Derbent'        => 'Derbent',
												'Emirgazi'       => 'Emirgazi',
												'Güneysınır'     => 'Güneysınır',
												'Halkapınar'     => 'Halkapınar',
												'Tuzlukçu'       => 'Tuzlukçu',
												'Yalıhüyük'      => 'Yalıhüyük',
										),
								43 =>
										array(
												'Altıntaş'       => 'Altıntaş',
												'Domaniç'        => 'Domaniç',
												'Emet'           => 'Emet',
												'Gediz'          => 'Gediz',
												'Kütahya Merkez' => 'Kütahya Merkez',
												'Simav'          => 'Simav',
												'Tavşanlı'       => 'Tavşanlı',
												'Aslanapa'       => 'Aslanapa',
												'Dumlupınar'     => 'Dumlupınar',
												'Hisarcık'       => 'Hisarcık',
												'Şaphane'        => 'Şaphane',
												'Çavdarhisar'    => 'Çavdarhisar',
												'Pazarlar'       => 'Pazarlar',
										),
								44 =>
										array(
												'Akçadağ'             => 'Akçadağ',
												'Arapgir'             => 'Arapgir',
												'Arguvan'             => 'Arguvan',
												'Darende'             => 'Darende',
												'Doğanşehir'          => 'Doğanşehir',
												'Hekimhan'            => 'Hekimhan',
												'Pütürge'             => 'Pütürge',
												'Yeşilyurt / Malatya' => 'Yeşilyurt / Malatya',
												'Battalgazi'          => 'Battalgazi',
												'Doğanyol'            => 'Doğanyol',
												'Kale / Malatya'      => 'Kale / Malatya',
												'Kuluncak'            => 'Kuluncak',
												'Yazıhan'             => 'Yazıhan',
										),
								45 =>
										array(
												'Akhisar'            => 'Akhisar',
												'Alaşehir'           => 'Alaşehir',
												'Demirci'            => 'Demirci',
												'Gördes'             => 'Gördes',
												'Kırkağaç'           => 'Kırkağaç',
												'Kula'               => 'Kula',
												'Salihli'            => 'Salihli',
												'Sarıgöl'            => 'Sarıgöl',
												'Saruhanlı'          => 'Saruhanlı',
												'Selendi'            => 'Selendi',
												'Soma'               => 'Soma',
												'Turgutlu'           => 'Turgutlu',
												'Ahmetli'            => 'Ahmetli',
												'Gölmarmara'         => 'Gölmarmara',
												'Köprübaşı / Manisa' => 'Köprübaşı / Manisa',
												'Şehzadeler'         => 'Şehzadeler',
												'Yunusemre'          => 'Yunusemre',
										),
								46 =>
										array(
												'Afşin'         => 'Afşin',
												'Andırın'       => 'Andırın',
												'Elbistan'      => 'Elbistan',
												'Göksun'        => 'Göksun',
												'Pazarcık'      => 'Pazarcık',
												'Türkoğlu'      => 'Türkoğlu',
												'Çağlayancerit' => 'Çağlayancerit',
												'Ekinözü'       => 'Ekinözü',
												'Nurhak'        => 'Nurhak',
												'Dulkadiroğlu'  => 'Dulkadiroğlu',
												'Onikişubat'    => 'Onikişubat',
										),
								47 =>
										array(
												'Derik'     => 'Derik',
												'Kızıltepe' => 'Kızıltepe',
												'Mazıdağı'  => 'Mazıdağı',
												'Midyat'    => 'Midyat',
												'Nusaybin'  => 'Nusaybin',
												'Ömerli'    => 'Ömerli',
												'Savur'     => 'Savur',
												'Dargeçit'  => 'Dargeçit',
												'Yeşilli'   => 'Yeşilli',
												'Artuklu'   => 'Artuklu',
										),
								48 =>
										array(
												'Bodrum'      => 'Bodrum',
												'Datça'       => 'Datça',
												'Fethiye'     => 'Fethiye',
												'Köyceğiz'    => 'Köyceğiz',
												'Marmaris'    => 'Marmaris',
												'Milas'       => 'Milas',
												'Ula'         => 'Ula',
												'Yatağan'     => 'Yatağan',
												'Dalaman'     => 'Dalaman',
												'Ortaca'      => 'Ortaca',
												'Kavaklıdere' => 'Kavaklıdere',
												'Menteşe'     => 'Menteşe',
												'Seydikemer'  => 'Seydikemer',
										),
								49 =>
										array(
												'Bulanık'    => 'Bulanık',
												'Malazgirt'  => 'Malazgirt',
												'Muş Merkez' => 'Muş Merkez',
												'Varto'      => 'Varto',
												'Hasköy'     => 'Hasköy',
												'Korkut'     => 'Korkut',
										),
								50 =>
										array(
												'Avanos'          => 'Avanos',
												'Derinkuyu'       => 'Derinkuyu',
												'Gülşehir'        => 'Gülşehir',
												'Hacıbektaş'      => 'Hacıbektaş',
												'Kozaklı'         => 'Kozaklı',
												'Nevşehir Merkez' => 'Nevşehir Merkez',
												'Ürgüp'           => 'Ürgüp',
												'Acıgöl'          => 'Acıgöl',
										),
								51 =>
										array(
												'Bor'          => 'Bor',
												'Çamardı'      => 'Çamardı',
												'Niğde Merkez' => 'Niğde Merkez',
												'Ulukışla'     => 'Ulukışla',
												'Altunhisar'   => 'Altunhisar',
												'Çiftlik'      => 'Çiftlik',
										),
								52 =>
										array(
												'Akkuş'         => 'Akkuş',
												'Aybastı'       => 'Aybastı',
												'Fatsa'         => 'Fatsa',
												'Gölköy'        => 'Gölköy',
												'Korgan'        => 'Korgan',
												'Kumru'         => 'Kumru',
												'Mesudiye'      => 'Mesudiye',
												'Perşembe'      => 'Perşembe',
												'Ulubey / Ordu' => 'Ulubey / Ordu',
												'Ünye'          => 'Ünye',
												'Gülyalı'       => 'Gülyalı',
												'Gürgentepe'    => 'Gürgentepe',
												'Çamaş'         => 'Çamaş',
												'Çatalpınar'    => 'Çatalpınar',
												'Çaybaşı'       => 'Çaybaşı',
												'İkizce'        => 'İkizce',
												'Kabadüz'       => 'Kabadüz',
												'Kabataş'       => 'Kabataş',
												'Altınordu'     => 'Altınordu',
										),
								53 =>
										array(
												'Ardeşen'      => 'Ardeşen',
												'Çamlıhemşin'  => 'Çamlıhemşin',
												'Çayeli'       => 'Çayeli',
												'Fındıklı'     => 'Fındıklı',
												'İkizdere'     => 'İkizdere',
												'Kalkandere'   => 'Kalkandere',
												'Pazar / Rize' => 'Pazar / Rize',
												'Rize Merkez'  => 'Rize Merkez',
												'Güneysu'      => 'Güneysu',
												'Derepazarı'   => 'Derepazarı',
												'Hemşin'       => 'Hemşin',
												'İyidere'      => 'İyidere',
										),
								54 =>
										array(
												'Akyazı'     => 'Akyazı',
												'Geyve'      => 'Geyve',
												'Hendek'     => 'Hendek',
												'Karasu'     => 'Karasu',
												'Kaynarca'   => 'Kaynarca',
												'Sapanca'    => 'Sapanca',
												'Kocaali'    => 'Kocaali',
												'Pamukova'   => 'Pamukova',
												'Taraklı'    => 'Taraklı',
												'Ferizli'    => 'Ferizli',
												'Karapürçek' => 'Karapürçek',
												'Söğütlü'    => 'Söğütlü',
												'Adapazarı'  => 'Adapazarı',
												'Arifiye'    => 'Arifiye',
												'Erenler'    => 'Erenler',
												'Serdivan'   => 'Serdivan',
										),
								55 =>
										array(
												'Alaçam'           => 'Alaçam',
												'Bafra'            => 'Bafra',
												'Çarşamba'         => 'Çarşamba',
												'Havza'            => 'Havza',
												'Kavak'            => 'Kavak',
												'Ladik'            => 'Ladik',
												'Terme'            => 'Terme',
												'Vezirköprü'       => 'Vezirköprü',
												'Asarcık'          => 'Asarcık',
												'19 Mayıs'         => '19 Mayıs',
												'Salıpazarı'       => 'Salıpazarı',
												'Tekkeköy'         => 'Tekkeköy',
												'Ayvacık / Samsun' => 'Ayvacık / Samsun',
												'Yakakent'         => 'Yakakent',
												'Atakum'           => 'Atakum',
												'Canik'            => 'Canik',
												'İlkadım'          => 'İlkadım',
										),
								56 =>
										array(
												'Baykan'       => 'Baykan',
												'Eruh'         => 'Eruh',
												'Kurtalan'     => 'Kurtalan',
												'Pervari'      => 'Pervari',
												'Siirt Merkez' => 'Siirt Merkez',
												'Şirvan'       => 'Şirvan',
												'Tillo'        => 'Tillo',
										),
								57 =>
										array(
												'Ayancık'      => 'Ayancık',
												'Boyabat'      => 'Boyabat',
												'Durağan'      => 'Durağan',
												'Erfelek'      => 'Erfelek',
												'Gerze'        => 'Gerze',
												'Sinop Merkez' => 'Sinop Merkez',
												'Türkeli'      => 'Türkeli',
												'Dikmen'       => 'Dikmen',
												'Saraydüzü'    => 'Saraydüzü',
										),
								58 =>
										array(
												'Divriği'            => 'Divriği',
												'Gemerek'            => 'Gemerek',
												'Gürün'              => 'Gürün',
												'Hafik'              => 'Hafik',
												'İmranlı'            => 'İmranlı',
												'Kangal'             => 'Kangal',
												'Koyulhisar'         => 'Koyulhisar',
												'Sivas Merkez'       => 'Sivas Merkez',
												'Suşehri'            => 'Suşehri',
												'Şarkışla'           => 'Şarkışla',
												'Yıldızeli'          => 'Yıldızeli',
												'Zara'               => 'Zara',
												'Akıncılar'          => 'Akıncılar',
												'Altınyayla / Sivas' => 'Altınyayla / Sivas',
												'Doğanşar'           => 'Doğanşar',
												'Gölova'             => 'Gölova',
												'Ulaş'               => 'Ulaş',
										),
								59 =>
										array(
												'Çerkezköy'        => 'Çerkezköy',
												'Çorlu'            => 'Çorlu',
												'Hayrabolu'        => 'Hayrabolu',
												'Malkara'          => 'Malkara',
												'Muratlı'          => 'Muratlı',
												'Saray / Tekirdağ' => 'Saray / Tekirdağ',
												'Şarköy'           => 'Şarköy',
												'Marmaraereğlisi'  => 'Marmaraereğlisi',
												'Ergene'           => 'Ergene',
												'Süleymanpaşa'     => 'Süleymanpaşa',
										),
								60 =>
										array(
												'Almus'             => 'Almus',
												'Artova'            => 'Artova',
												'Erbaa'             => 'Erbaa',
												'Niksar'            => 'Niksar',
												'Reşadiye'          => 'Reşadiye',
												'Tokat Merkez'      => 'Tokat Merkez',
												'Turhal'            => 'Turhal',
												'Zile'              => 'Zile',
												'Pazar / Tokat'     => 'Pazar / Tokat',
												'Yeşilyurt / Tokat' => 'Yeşilyurt / Tokat',
												'Başçiftlik'        => 'Başçiftlik',
												'Sulusaray'         => 'Sulusaray',
										),
								61 =>
										array(
												'Akçaabat'            => 'Akçaabat',
												'Araklı'              => 'Araklı',
												'Arsin'               => 'Arsin',
												'Çaykara'             => 'Çaykara',
												'Maçka'               => 'Maçka',
												'Of'                  => 'Of',
												'Sürmene'             => 'Sürmene',
												'Tonya'               => 'Tonya',
												'Vakfıkebir'          => 'Vakfıkebir',
												'Yomra'               => 'Yomra',
												'Beşikdüzü'           => 'Beşikdüzü',
												'Şalpazarı'           => 'Şalpazarı',
												'Çarşıbaşı'           => 'Çarşıbaşı',
												'Dernekpazarı'        => 'Dernekpazarı',
												'Düzköy'              => 'Düzköy',
												'Hayrat'              => 'Hayrat',
												'Köprübaşı / Trabzon' => 'Köprübaşı / Trabzon',
												'Ortahisar'           => 'Ortahisar',
										),
								62 =>
										array(
												'Çemişgezek'       => 'Çemişgezek',
												'Hozat'            => 'Hozat',
												'Mazgirt'          => 'Mazgirt',
												'Nazımiye'         => 'Nazımiye',
												'Ovacık / Tunceli' => 'Ovacık / Tunceli',
												'Pertek'           => 'Pertek',
												'Pülümür'          => 'Pülümür',
												'Tunceli Merkez'   => 'Tunceli Merkez',
										),
								63 =>
										array(
												'Akçakale'    => 'Akçakale',
												'Birecik'     => 'Birecik',
												'Bozova'      => 'Bozova',
												'Ceylanpınar' => 'Ceylanpınar',
												'Halfeti'     => 'Halfeti',
												'Hilvan'      => 'Hilvan',
												'Siverek'     => 'Siverek',
												'Suruç'       => 'Suruç',
												'Viranşehir'  => 'Viranşehir',
												'Harran'      => 'Harran',
												'Eyyübiye'    => 'Eyyübiye',
												'Haliliye'    => 'Haliliye',
												'Karaköprü'   => 'Karaköprü',
										),
								64 =>
										array(
												'Banaz'         => 'Banaz',
												'Eşme'          => 'Eşme',
												'Karahallı'     => 'Karahallı',
												'Sivaslı'       => 'Sivaslı',
												'Ulubey / Uşak' => 'Ulubey / Uşak',
												'Uşak Merkez'   => 'Uşak Merkez',
										),
								65 =>
										array(
												'Başkale'       => 'Başkale',
												'Çatak'         => 'Çatak',
												'Erciş'         => 'Erciş',
												'Gevaş'         => 'Gevaş',
												'Gürpınar'      => 'Gürpınar',
												'Muradiye'      => 'Muradiye',
												'Özalp'         => 'Özalp',
												'Bahçesaray'    => 'Bahçesaray',
												'Çaldıran'      => 'Çaldıran',
												'Edremit / Van' => 'Edremit / Van',
												'Saray / Van'   => 'Saray / Van',
												'İpekyolu'      => 'İpekyolu',
												'Tuşba'         => 'Tuşba',
										),
								66 =>
										array(
												'Akdağmadeni'       => 'Akdağmadeni',
												'Boğazlıyan'        => 'Boğazlıyan',
												'Çayıralan'         => 'Çayıralan',
												'Çekerek'           => 'Çekerek',
												'Sarıkaya'          => 'Sarıkaya',
												'Sorgun'            => 'Sorgun',
												'Şefaatli'          => 'Şefaatli',
												'Yerköy'            => 'Yerköy',
												'Yozgat Merkez'     => 'Yozgat Merkez',
												'Aydıncık / Yozgat' => 'Aydıncık / Yozgat',
												'Çandır'            => 'Çandır',
												'Kadışehri'         => 'Kadışehri',
												'Saraykent'         => 'Saraykent',
												'Yenifakılı'        => 'Yenifakılı',
										),
								67 =>
										array(
												'Çaycuma'            => 'Çaycuma',
												'Devrek'             => 'Devrek',
												'Ereğli / Zonguldak' => 'Ereğli / Zonguldak',
												'Zonguldak Merkez'   => 'Zonguldak Merkez',
												'Alaplı'             => 'Alaplı',
												'Gökçebey'           => 'Gökçebey',
										),
								68 =>
										array(
												'Aksaray Merkez'    => 'Aksaray Merkez',
												'Ortaköy / Aksaray' => 'Ortaköy / Aksaray',
												'Ağaçören'          => 'Ağaçören',
												'Güzelyurt'         => 'Güzelyurt',
												'Sarıyahşi'         => 'Sarıyahşi',
												'Eskil'             => 'Eskil',
												'Gülağaç'           => 'Gülağaç',
										),
								69 =>
										array(
												'Bayburt Merkez' => 'Bayburt Merkez',
												'Aydıntepe'      => 'Aydıntepe',
												'Demirözü'       => 'Demirözü',
										),
								70 =>
										array(
												'Ermenek'        => 'Ermenek',
												'Karaman Merkez' => 'Karaman Merkez',
												'Ayrancı'        => 'Ayrancı',
												'Kazımkarabekir' => 'Kazımkarabekir',
												'Başyayla'       => 'Başyayla',
												'Sarıveliler'    => 'Sarıveliler',
										),
								71 =>
										array(
												'Delice'           => 'Delice',
												'Keskin'           => 'Keskin',
												'Kırıkkale Merkez' => 'Kırıkkale Merkez',
												'Sulakyurt'        => 'Sulakyurt',
												'Bahşili'          => 'Bahşili',
												'Balışeyh'         => 'Balışeyh',
												'Çelebi'           => 'Çelebi',
												'Karakeçili'       => 'Karakeçili',
												'Yahşihan'         => 'Yahşihan',
										),
								72 =>
										array(
												'Batman Merkez' => 'Batman Merkez',
												'Beşiri'        => 'Beşiri',
												'Gercüş'        => 'Gercüş',
												'Kozluk'        => 'Kozluk',
												'Sason'         => 'Sason',
												'Hasankeyf'     => 'Hasankeyf',
										),
								73 =>
										array(
												'Beytüşşebap'   => 'Beytüşşebap',
												'Cizre'         => 'Cizre',
												'İdil'          => 'İdil',
												'Silopi'        => 'Silopi',
												'Şırnak Merkez' => 'Şırnak Merkez',
												'Uludere'       => 'Uludere',
												'Güçlükonak'    => 'Güçlükonak',
										),
								74 =>
										array(
												'Bartın Merkez' => 'Bartın Merkez',
												'Kurucaşile'    => 'Kurucaşile',
												'Ulus'          => 'Ulus',
												'Amasra'        => 'Amasra',
										),
								75 =>
										array(
												'Ardahan Merkez' => 'Ardahan Merkez',
												'Çıldır'         => 'Çıldır',
												'Göle'           => 'Göle',
												'Hanak'          => 'Hanak',
												'Posof'          => 'Posof',
												'Damal'          => 'Damal',
										),
								76 =>
										array(
												'Aralık'       => 'Aralık',
												'Iğdır Merkez' => 'Iğdır Merkez',
												'Tuzluca'      => 'Tuzluca',
												'Karakoyunlu'  => 'Karakoyunlu',
										),
								77 =>
										array(
												'Yalova Merkez' => 'Yalova Merkez',
												'Altınova'      => 'Altınova',
												'Armutlu'       => 'Armutlu',
												'Çınarcık'      => 'Çınarcık',
												'Çiftlikköy'    => 'Çiftlikköy',
												'Termal'        => 'Termal',
										),
								78 =>
										array(
												'Eflani'           => 'Eflani',
												'Eskipazar'        => 'Eskipazar',
												'Karabük Merkez'   => 'Karabük Merkez',
												'Ovacık / Karabük' => 'Ovacık / Karabük',
												'Safranbolu'       => 'Safranbolu',
												'Yenice / Karabük' => 'Yenice / Karabük',
										),
								79 =>
										array(
												'Kilis Merkez' => 'Kilis Merkez',
												'Elbeyli'      => 'Elbeyli',
												'Musabeyli'    => 'Musabeyli',
												'Polateli'     => 'Polateli',
										),
								80 =>
										array(
												'Bahçe'           => 'Bahçe',
												'Kadirli'         => 'Kadirli',
												'Osmaniye Merkez' => 'Osmaniye Merkez',
												'Düziçi'          => 'Düziçi',
												'Hasanbeyli'      => 'Hasanbeyli',
												'Sumbas'          => 'Sumbas',
												'Toprakkale'      => 'Toprakkale',
										),
								81 =>
										array(
												'Akçakoca'     => 'Akçakoca',
												'Düzce Merkez' => 'Düzce Merkez',
												'Yığılca'      => 'Yığılca',
												'Cumayeri'     => 'Cumayeri',
												'Gölyaka'      => 'Gölyaka',
												'Çilimli'      => 'Çilimli',
												'Gümüşova'     => 'Gümüşova',
												'Kaynaşlı'     => 'Kaynaşlı',
										),
						) ),
						'optionType'  => 'general',
						'created_at'  => date( 'Y-m-d H:i:s' )
				),
				array( 'optionKey'   => 'postTypes',
							 'optionValue' => serialize( array(
									 'news'    => 'News',
									 'slider'  => 'Slider',
									 'service' => 'Service',
									 'product' => 'Product' ) ),
							 'optionType'  => 'general',
							 'created_at'  => date( 'Y-m-d H:i:s' )
				),
				array( 'optionKey' => 'mainMailAddress', 'optionValue' => $mainMailAddress, 'optionType' => 'general', 'created_at' => date( 'Y-m-d H:i:s' ) ),
				array('optionKey'=>'duesAmount','optionValue'=>10,'optionType'=>'general','created_at'  => date( 'Y-m-d H:i:s' ))
		) );
		// Konsol çıktısını verelim
		$this->command->info( 'Örnek veriler eklendi' );
	}
}