@extends('template.default')
@section('header')
<div class="body1">
	<div class="body2">
		<div class="body5">
			<div class="main zerogrid">
				<!-- header -->
				<header>
					<div class="wrapper row">
						<h1><a id="logo" href="{{ URL::route('home') }}"><img src="{{ URL::asset('assets/images/logo.png') }}"></a></h1>
						<nav>
							<ul id="menu">
								<li id="nav1"><a href="{{ URL::route('home') }}">Home<span>Welcome!</span></a></li>
								<li id="nav2" class="active"><a href="{{ URL::route('news') }}">News<span>Fresh</span></a></li>
								<li id="nav3"><a href="{{ URL::route('services') }}">Services<span>for you</span></a></li>
								<li id="nav4"><a href="{{ URL::route('products') }}">Products<span>The best</span></a></li>
								<li id="nav5"><a href="{{ URL::route('contacts') }}">Contacts<span>Our Address</span></a></li>
							</ul>
						</nav>
					</div>
				</header>
				<!-- header end-->
			</div>
		</div>
	</div>
</div>
@stop

@section('content')
<div class="body3">
	<div class="main zerogrid">
		<!-- content -->
		<article id="content">
			<div class="wrapper tabs">
				<div id="tab1" class="tab-content" style="display: block;">
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="28" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>28</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Lorem " style="width: 90px; height: 33px;"><canvas width="118" height="40" style="width: 118px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Lorem </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ipsum " style="width: 86px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ipsum </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="amet " style="width: 71px; height: 33px;"><canvas width="100" height="40" style="width: 100px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>amet </cufontext></cufon><cufon class="cufon cufon-canvas" alt="consectetur " style="width: 157px; height: 33px;"><canvas width="185" height="40" style="width: 185px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>consectetur </cufontext></cufon><cufon class="cufon cufon-canvas" alt="adipisicing " style="width: 143px; height: 33px;"><canvas width="172" height="40" style="width: 172px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>adipisicing </cufontext></cufon><cufon class="cufon cufon-canvas" alt="elit" style="width: 36px; height: 33px;"><canvas width="65" height="40" style="width: 65px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>elit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="{{ URL::asset('assets/images/page2_img1.jpg') }}"></figure>
						<p class="pad_bot1">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="25" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>25</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Duis " style="width: 65px; height: 33px;"><canvas width="94" height="40" style="width: 94px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Duis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="aute " style="width: 62px; height: 33px;"><canvas width="90" height="40" style="width: 90px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>aute </cufontext></cufon><cufon class="cufon cufon-canvas" alt="irure " style="width: 66px; height: 33px;"><canvas width="95" height="40" style="width: 95px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>irure </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="in " style="width: 31px; height: 33px;"><canvas width="59" height="40" style="width: 59px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>in </cufontext></cufon><cufon class="cufon cufon-canvas" alt="reprehenderit" style="width: 166px; height: 33px;"><canvas width="194" height="40" style="width: 194px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>reprehenderit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="{{ URL::asset('assets/images/page2_img2.jpg') }}"></figure>
						<p class="pad_bot1">Sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="21" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>21</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Sed " style="width: 57px; height: 33px;"><canvas width="86" height="40" style="width: 86px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Sed </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ut " style="width: 33px; height: 33px;"><canvas width="61" height="40" style="width: 61px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ut </cufontext></cufon><cufon class="cufon cufon-canvas" alt="perspiciatis " style="width: 152px; height: 33px;"><canvas width="181" height="40" style="width: 181px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>perspiciatis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="unde " style="width: 71px; height: 33px;"><canvas width="99" height="40" style="width: 99px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>unde </cufontext></cufon><cufon class="cufon cufon-canvas" alt="omnis " style="width: 87px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>omnis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="iste " style="width: 53px; height: 33px;"><canvas width="81" height="40" style="width: 81px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>iste </cufontext></cufon><cufon class="cufon cufon-canvas" alt="natus " style="width: 78px; height: 33px;"><canvas width="106" height="40" style="width: 106px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>natus </cufontext></cufon><cufon class="cufon cufon-canvas" alt="error " style="width: 69px; height: 33px;"><canvas width="97" height="40" style="width: 97px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>error </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="voluptatem" style="width: 139px; height: 33px;"><canvas width="151" height="40" style="width: 151px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>voluptatem</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="{{ URL::asset('assets/images/page2_img3.jpg') }}"></figure>
						<p class="pad_bot1">Vel illum qui dolorem eum fugiat quo voluptas nulla pariatur. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis.</p>
						<a class="link1" href="#">Read More</a>
					</div>
				</div>
				<div id="tab2" class="tab-content" style="display: none;">

					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="25" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>25</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Duis " style="width: 65px; height: 33px;"><canvas width="94" height="40" style="width: 94px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Duis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="aute " style="width: 62px; height: 33px;"><canvas width="90" height="40" style="width: 90px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>aute </cufontext></cufon><cufon class="cufon cufon-canvas" alt="irure " style="width: 66px; height: 33px;"><canvas width="95" height="40" style="width: 95px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>irure </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="in " style="width: 31px; height: 33px;"><canvas width="59" height="40" style="width: 59px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>in </cufontext></cufon><cufon class="cufon cufon-canvas" alt="reprehenderit" style="width: 166px; height: 33px;"><canvas width="194" height="40" style="width: 194px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>reprehenderit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="{{ URL::asset('assets/images/page2_img2.jpg') }}"></figure>
						<p class="pad_bot1">Sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="21" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>21</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Sed " style="width: 57px; height: 33px;"><canvas width="86" height="40" style="width: 86px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Sed </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ut " style="width: 33px; height: 33px;"><canvas width="61" height="40" style="width: 61px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ut </cufontext></cufon><cufon class="cufon cufon-canvas" alt="perspiciatis " style="width: 152px; height: 33px;"><canvas width="181" height="40" style="width: 181px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>perspiciatis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="unde " style="width: 71px; height: 33px;"><canvas width="99" height="40" style="width: 99px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>unde </cufontext></cufon><cufon class="cufon cufon-canvas" alt="omnis " style="width: 87px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>omnis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="iste " style="width: 53px; height: 33px;"><canvas width="81" height="40" style="width: 81px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>iste </cufontext></cufon><cufon class="cufon cufon-canvas" alt="natus " style="width: 78px; height: 33px;"><canvas width="106" height="40" style="width: 106px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>natus </cufontext></cufon><cufon class="cufon cufon-canvas" alt="error " style="width: 69px; height: 33px;"><canvas width="97" height="40" style="width: 97px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>error </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="voluptatem" style="width: 139px; height: 33px;"><canvas width="151" height="40" style="width: 151px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>voluptatem</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="{{ URL::asset('assets/images/page2_img3.jpg') }}"></figure>
						<p class="pad_bot1">Vel illum qui dolorem eum fugiat quo voluptas nulla pariatur. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="28" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>28</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Lorem " style="width: 90px; height: 33px;"><canvas width="118" height="40" style="width: 118px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Lorem </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ipsum " style="width: 86px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ipsum </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="amet " style="width: 71px; height: 33px;"><canvas width="100" height="40" style="width: 100px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>amet </cufontext></cufon><cufon class="cufon cufon-canvas" alt="consectetur " style="width: 157px; height: 33px;"><canvas width="185" height="40" style="width: 185px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>consectetur </cufontext></cufon><cufon class="cufon cufon-canvas" alt="adipisicing " style="width: 143px; height: 33px;"><canvas width="172" height="40" style="width: 172px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>adipisicing </cufontext></cufon><cufon class="cufon cufon-canvas" alt="elit" style="width: 36px; height: 33px;"><canvas width="65" height="40" style="width: 65px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>elit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="{{ URL::asset('assets/images/page2_img1.jpg') }}"></figure>
						<p class="pad_bot1">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.</p>
						<a class="link1" href="#">Read More</a>
					</div>
				</div>
				<div id="tab3" class="tab-content" style="display: none;">
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="21" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>21</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Sed " style="width: 57px; height: 33px;"><canvas width="86" height="40" style="width: 86px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Sed </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ut " style="width: 33px; height: 33px;"><canvas width="61" height="40" style="width: 61px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ut </cufontext></cufon><cufon class="cufon cufon-canvas" alt="perspiciatis " style="width: 152px; height: 33px;"><canvas width="181" height="40" style="width: 181px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>perspiciatis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="unde " style="width: 71px; height: 33px;"><canvas width="99" height="40" style="width: 99px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>unde </cufontext></cufon><cufon class="cufon cufon-canvas" alt="omnis " style="width: 87px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>omnis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="iste " style="width: 53px; height: 33px;"><canvas width="81" height="40" style="width: 81px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>iste </cufontext></cufon><cufon class="cufon cufon-canvas" alt="natus " style="width: 78px; height: 33px;"><canvas width="106" height="40" style="width: 106px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>natus </cufontext></cufon><cufon class="cufon cufon-canvas" alt="error " style="width: 69px; height: 33px;"><canvas width="97" height="40" style="width: 97px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>error </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="voluptatem" style="width: 139px; height: 33px;"><canvas width="151" height="40" style="width: 151px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>voluptatem</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img3.jpg"></figure>
						<p class="pad_bot1">Vel illum qui dolorem eum fugiat quo voluptas nulla pariatur. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="28" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>28</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Lorem " style="width: 90px; height: 33px;"><canvas width="118" height="40" style="width: 118px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Lorem </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ipsum " style="width: 86px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ipsum </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="amet " style="width: 71px; height: 33px;"><canvas width="100" height="40" style="width: 100px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>amet </cufontext></cufon><cufon class="cufon cufon-canvas" alt="consectetur " style="width: 157px; height: 33px;"><canvas width="185" height="40" style="width: 185px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>consectetur </cufontext></cufon><cufon class="cufon cufon-canvas" alt="adipisicing " style="width: 143px; height: 33px;"><canvas width="172" height="40" style="width: 172px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>adipisicing </cufontext></cufon><cufon class="cufon cufon-canvas" alt="elit" style="width: 36px; height: 33px;"><canvas width="65" height="40" style="width: 65px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>elit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img1.jpg"></figure>
						<p class="pad_bot1">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="25" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>25</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Duis " style="width: 65px; height: 33px;"><canvas width="94" height="40" style="width: 94px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Duis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="aute " style="width: 62px; height: 33px;"><canvas width="90" height="40" style="width: 90px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>aute </cufontext></cufon><cufon class="cufon cufon-canvas" alt="irure " style="width: 66px; height: 33px;"><canvas width="95" height="40" style="width: 95px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>irure </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="in " style="width: 31px; height: 33px;"><canvas width="59" height="40" style="width: 59px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>in </cufontext></cufon><cufon class="cufon cufon-canvas" alt="reprehenderit" style="width: 166px; height: 33px;"><canvas width="194" height="40" style="width: 194px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>reprehenderit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img2.jpg"></figure>
						<p class="pad_bot1">Sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.</p>
						<a class="link1" href="#">Read More</a>
					</div>
				</div>
				<div id="tab4" class="tab-content" style="display: none;">
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="28" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>28</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Lorem " style="width: 90px; height: 33px;"><canvas width="118" height="40" style="width: 118px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Lorem </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ipsum " style="width: 86px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ipsum </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="amet " style="width: 71px; height: 33px;"><canvas width="100" height="40" style="width: 100px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>amet </cufontext></cufon><cufon class="cufon cufon-canvas" alt="consectetur " style="width: 157px; height: 33px;"><canvas width="185" height="40" style="width: 185px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>consectetur </cufontext></cufon><cufon class="cufon cufon-canvas" alt="adipisicing " style="width: 143px; height: 33px;"><canvas width="172" height="40" style="width: 172px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>adipisicing </cufontext></cufon><cufon class="cufon cufon-canvas" alt="elit" style="width: 36px; height: 33px;"><canvas width="65" height="40" style="width: 65px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>elit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img1.jpg"></figure>
						<p class="pad_bot1">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="25" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>25</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Duis " style="width: 65px; height: 33px;"><canvas width="94" height="40" style="width: 94px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Duis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="aute " style="width: 62px; height: 33px;"><canvas width="90" height="40" style="width: 90px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>aute </cufontext></cufon><cufon class="cufon cufon-canvas" alt="irure " style="width: 66px; height: 33px;"><canvas width="95" height="40" style="width: 95px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>irure </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="in " style="width: 31px; height: 33px;"><canvas width="59" height="40" style="width: 59px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>in </cufontext></cufon><cufon class="cufon cufon-canvas" alt="reprehenderit" style="width: 166px; height: 33px;"><canvas width="194" height="40" style="width: 194px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>reprehenderit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img2.jpg"></figure>
						<p class="pad_bot1">Sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="21" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>21</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Sed " style="width: 57px; height: 33px;"><canvas width="86" height="40" style="width: 86px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Sed </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ut " style="width: 33px; height: 33px;"><canvas width="61" height="40" style="width: 61px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ut </cufontext></cufon><cufon class="cufon cufon-canvas" alt="perspiciatis " style="width: 152px; height: 33px;"><canvas width="181" height="40" style="width: 181px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>perspiciatis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="unde " style="width: 71px; height: 33px;"><canvas width="99" height="40" style="width: 99px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>unde </cufontext></cufon><cufon class="cufon cufon-canvas" alt="omnis " style="width: 87px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>omnis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="iste " style="width: 53px; height: 33px;"><canvas width="81" height="40" style="width: 81px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>iste </cufontext></cufon><cufon class="cufon cufon-canvas" alt="natus " style="width: 78px; height: 33px;"><canvas width="106" height="40" style="width: 106px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>natus </cufontext></cufon><cufon class="cufon cufon-canvas" alt="error " style="width: 69px; height: 33px;"><canvas width="97" height="40" style="width: 97px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>error </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="voluptatem" style="width: 139px; height: 33px;"><canvas width="151" height="40" style="width: 151px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>voluptatem</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img3.jpg"></figure>
						<p class="pad_bot1">Vel illum qui dolorem eum fugiat quo voluptas nulla pariatur. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis.</p>
						<a class="link1" href="#">Read More</a>
					</div>
				</div>
				<div id="tab5" class="tab-content" style="display: none;">

					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="25" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>25</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Duis " style="width: 65px; height: 33px;"><canvas width="94" height="40" style="width: 94px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Duis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="aute " style="width: 62px; height: 33px;"><canvas width="90" height="40" style="width: 90px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>aute </cufontext></cufon><cufon class="cufon cufon-canvas" alt="irure " style="width: 66px; height: 33px;"><canvas width="95" height="40" style="width: 95px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>irure </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="in " style="width: 31px; height: 33px;"><canvas width="59" height="40" style="width: 59px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>in </cufontext></cufon><cufon class="cufon cufon-canvas" alt="reprehenderit" style="width: 166px; height: 33px;"><canvas width="194" height="40" style="width: 194px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>reprehenderit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img2.jpg"></figure>
						<p class="pad_bot1">Sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="21" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>21</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Sed " style="width: 57px; height: 33px;"><canvas width="86" height="40" style="width: 86px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Sed </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ut " style="width: 33px; height: 33px;"><canvas width="61" height="40" style="width: 61px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ut </cufontext></cufon><cufon class="cufon cufon-canvas" alt="perspiciatis " style="width: 152px; height: 33px;"><canvas width="181" height="40" style="width: 181px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>perspiciatis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="unde " style="width: 71px; height: 33px;"><canvas width="99" height="40" style="width: 99px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>unde </cufontext></cufon><cufon class="cufon cufon-canvas" alt="omnis " style="width: 87px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>omnis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="iste " style="width: 53px; height: 33px;"><canvas width="81" height="40" style="width: 81px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>iste </cufontext></cufon><cufon class="cufon cufon-canvas" alt="natus " style="width: 78px; height: 33px;"><canvas width="106" height="40" style="width: 106px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>natus </cufontext></cufon><cufon class="cufon cufon-canvas" alt="error " style="width: 69px; height: 33px;"><canvas width="97" height="40" style="width: 97px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>error </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="voluptatem" style="width: 139px; height: 33px;"><canvas width="151" height="40" style="width: 151px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>voluptatem</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img3.jpg"></figure>
						<p class="pad_bot1">Vel illum qui dolorem eum fugiat quo voluptas nulla pariatur. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="28" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>28</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Lorem " style="width: 90px; height: 33px;"><canvas width="118" height="40" style="width: 118px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Lorem </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ipsum " style="width: 86px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ipsum </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="amet " style="width: 71px; height: 33px;"><canvas width="100" height="40" style="width: 100px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>amet </cufontext></cufon><cufon class="cufon cufon-canvas" alt="consectetur " style="width: 157px; height: 33px;"><canvas width="185" height="40" style="width: 185px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>consectetur </cufontext></cufon><cufon class="cufon cufon-canvas" alt="adipisicing " style="width: 143px; height: 33px;"><canvas width="172" height="40" style="width: 172px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>adipisicing </cufontext></cufon><cufon class="cufon cufon-canvas" alt="elit" style="width: 36px; height: 33px;"><canvas width="65" height="40" style="width: 65px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>elit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img1.jpg"></figure>
						<p class="pad_bot1">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.</p>
						<a class="link1" href="#">Read More</a>
					</div>
				</div>
				<div id="tab6" class="tab-content" style="display: none;">
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="21" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>21</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Sed " style="width: 57px; height: 33px;"><canvas width="86" height="40" style="width: 86px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Sed </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ut " style="width: 33px; height: 33px;"><canvas width="61" height="40" style="width: 61px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ut </cufontext></cufon><cufon class="cufon cufon-canvas" alt="perspiciatis " style="width: 152px; height: 33px;"><canvas width="181" height="40" style="width: 181px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>perspiciatis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="unde " style="width: 71px; height: 33px;"><canvas width="99" height="40" style="width: 99px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>unde </cufontext></cufon><cufon class="cufon cufon-canvas" alt="omnis " style="width: 87px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>omnis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="iste " style="width: 53px; height: 33px;"><canvas width="81" height="40" style="width: 81px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>iste </cufontext></cufon><cufon class="cufon cufon-canvas" alt="natus " style="width: 78px; height: 33px;"><canvas width="106" height="40" style="width: 106px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>natus </cufontext></cufon><cufon class="cufon cufon-canvas" alt="error " style="width: 69px; height: 33px;"><canvas width="97" height="40" style="width: 97px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>error </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="voluptatem" style="width: 139px; height: 33px;"><canvas width="151" height="40" style="width: 151px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>voluptatem</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img3.jpg"></figure>
						<p class="pad_bot1">Vel illum qui dolorem eum fugiat quo voluptas nulla pariatur. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="28" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>28</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Lorem " style="width: 90px; height: 33px;"><canvas width="118" height="40" style="width: 118px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Lorem </cufontext></cufon><cufon class="cufon cufon-canvas" alt="ipsum " style="width: 86px; height: 33px;"><canvas width="115" height="40" style="width: 115px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>ipsum </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="sit " style="width: 38px; height: 33px;"><canvas width="67" height="40" style="width: 67px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>sit </cufontext></cufon><cufon class="cufon cufon-canvas" alt="amet " style="width: 71px; height: 33px;"><canvas width="100" height="40" style="width: 100px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>amet </cufontext></cufon><cufon class="cufon cufon-canvas" alt="consectetur " style="width: 157px; height: 33px;"><canvas width="185" height="40" style="width: 185px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>consectetur </cufontext></cufon><cufon class="cufon cufon-canvas" alt="adipisicing " style="width: 143px; height: 33px;"><canvas width="172" height="40" style="width: 172px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>adipisicing </cufontext></cufon><cufon class="cufon cufon-canvas" alt="elit" style="width: 36px; height: 33px;"><canvas width="65" height="40" style="width: 65px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>elit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img1.jpg"></figure>
						<p class="pad_bot1">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.</p>
						<a class="link1" href="#">Read More</a>
					</div>
					<h5><span class="dropcap"><strong><cufon class="cufon cufon-canvas" alt="25" style="width: 31px; height: 34px;"><canvas width="52" height="41" style="width: 52px; height: 41px; top: -7px; left: -1px;"></canvas><cufontext>25</cufontext></cufon></strong><span><cufon class="cufon cufon-canvas" alt="06" style="width: 15px; height: 14px;"><canvas width="23" height="17" style="width: 23px; height: 17px; top: -3px; left: -1px;"></canvas><cufontext>06</cufontext></cufon></span></span><cufon class="cufon cufon-canvas" alt="Duis " style="width: 65px; height: 33px;"><canvas width="94" height="40" style="width: 94px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>Duis </cufontext></cufon><cufon class="cufon cufon-canvas" alt="aute " style="width: 62px; height: 33px;"><canvas width="90" height="40" style="width: 90px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>aute </cufontext></cufon><cufon class="cufon cufon-canvas" alt="irure " style="width: 66px; height: 33px;"><canvas width="95" height="40" style="width: 95px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>irure </cufontext></cufon><cufon class="cufon cufon-canvas" alt="dolor " style="width: 73px; height: 33px;"><canvas width="101" height="40" style="width: 101px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>dolor </cufontext></cufon><cufon class="cufon cufon-canvas" alt="in " style="width: 31px; height: 33px;"><canvas width="59" height="40" style="width: 59px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>in </cufontext></cufon><cufon class="cufon cufon-canvas" alt="reprehenderit" style="width: 166px; height: 33px;"><canvas width="194" height="40" style="width: 194px; height: 40px; top: -7px; left: -2px;"></canvas><cufontext>reprehenderit</cufontext></cufon></h5>
					<div class="wrapper pad_bot2">
						<figure class="left marg_right1"><img alt="" src="images/page2_img2.jpg"></figure>
						<p class="pad_bot1">Sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.</p>
						<a class="link1" href="#">Read More</a>
					</div>
				</div>
				<ul class="nav">
					<li class="selected"><a href="#tab1"><cufon class="cufon cufon-canvas" alt="1" style="width: 10px; height: 19px;"><canvas width="22" height="23" style="width: 22px; height: 23px; top: -4px; left: -1px;"></canvas><cufontext>1</cufontext></cufon></a></li>
					<li><a href="#tab2"><cufon class="cufon cufon-canvas" alt="2" style="width: 10px; height: 19px;"><canvas width="22" height="23" style="width: 22px; height: 23px; top: -4px; left: -1px;"></canvas><cufontext>2</cufontext></cufon></a></li>
					<li><a href="#tab3"><cufon class="cufon cufon-canvas" alt="3" style="width: 10px; height: 19px;"><canvas width="22" height="23" style="width: 22px; height: 23px; top: -4px; left: -1px;"></canvas><cufontext>3</cufontext></cufon></a></li>
					<li><a href="#tab4"><cufon class="cufon cufon-canvas" alt="4" style="width: 10px; height: 19px;"><canvas width="22" height="23" style="width: 22px; height: 23px; top: -4px; left: -1px;"></canvas><cufontext>4</cufontext></cufon></a></li>
					<li><a href="#tab5"><cufon class="cufon cufon-canvas" alt="5" style="width: 10px; height: 19px;"><canvas width="22" height="23" style="width: 22px; height: 23px; top: -4px; left: -1px;"></canvas><cufontext>5</cufontext></cufon></a></li>
					<li><a href="#tab6"><cufon class="cufon cufon-canvas" alt="6" style="width: 10px; height: 19px;"><canvas width="22" height="23" style="width: 22px; height: 23px; top: -4px; left: -1px;"></canvas><cufontext>6</cufontext></cufon></a></li>
				</ul>
			</div>

		</article>
	</div>
</div>
@stop
